const posts = [
  {
    title: "Mod Skin FF OB54 V20 Set Đồ Thỏ Thiên Hà Và Thỏ Đen",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v20-54.jpg",
    link: "OB54/v20-54.html",
  },
  {
    title: "Mod Skin FF OB54 V19 Hoạt Ảnh Hồi Máu Thần Ma",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v19-54.jpg",
    link: "OB54/v19-54.html",
  },
  {
    title: "Mod Skin FF OB54 V18 Set Đồ Áo Nagi và isagi",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v18-54.jpg",
    link: "OB54/v18-54.html",
  },
  {
    title: "Mod Skin FF OB54 V17 Set Đồ Tuyển Thủ Cyrus",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v17-54.jpg",
    link: "OB54/v17-54.html",
  },
  {
    title: "Mod Skin FF OB54 V16 Tung Tung Và Squid Game",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v16-54.jpg",
    link: "OB54/v16-54.html",
  },
  {
    title: "Mod Skin FF OB54 V15 Set Đồ Đôi Áo Đá Bóng Bá Sàn",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v15-54.jpg",
    link: "OB54/v15-54.html",
  },
  {
    title: "Mod Skin FF OB54 V14 Set Đồ Đôi Áo Blue Lock Bá Sàn",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v14-54.jpg",
    link: "OB54/v14-54.html",
  },
  {
    title: "Mod Skin FF OB54 V13 Hoạt Ảnh Mộng Cảnh",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v13-54.jpg",
    link: "OB54/v13-54.html",
  },
  {
    title: "Mod Skin FF OB54 V12 Súng M1887 Thánh Phồng Và Vũ Trụ Hủy Diệt",
    desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    img: "images/v12-54.jpg",
    link: "OB54/v12-54.html",
  },
];
