const posts = [
  {
    title: "Mod Skin FF OB54 V29 Hành động thành nắm đấm",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Súng: M590 Phong Xà",
    // desc: "Súng: Phong Xà",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    desc: "Hành động: Bắn nè hoặc Rét Run",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v29-54.jpg",
    link: "OB54/v29-54.html",
  },
  {
    title: "Mod Skin FF OB54 V28 Set Đồ Bá Sàn FF",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Súng: M590 Phong Xà",
    // desc: "Súng: Phong Xà",
    // desc: "Nhân Vật: Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè hoặc Rét Run",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v28-54.jpg",
    link: "OB54/v28-54.html",
  },
  {
    title: "Mod Skin FF OB54 V27 Combo 8 súng phong xà",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Súng: M590 Phong Xà",
    desc: "Súng: Phong Xà",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v27-54.jpg",
    link: "OB54/v27-54.html",
  },
  {
    title: "Mod Skin FF OB54 V26 M590 Đa Điện Và Mega",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Súng: M590 Phong Xà",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v26-54.jpg",
    link: "OB54/v26-54.html",
  },
  {
    title: "Mod Skin FF OB54 V25 Set Đồ Bá Sàn",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v25-54.jpg",
    link: "OB54/v25-54.html",
  },
  {
    title: "Mod Skin FF OB54 V23 Set Đồ Áo Họa Điểu",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v23-54.jpg",
    link: "OB54/v23-54.html",
  },
  {
    title: "Mod Skin FF OB54 V Test Hành động diệt địch M1887 VQC",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    desc: "Hòm Xác: Chất độc trong shop",

    img: "images/v-test-54.jpg",
    link: "OB54/v-test-54.html",
  },
  {
    title: "Mod Skin FF OB54 V21 Set Đồ Áo Mu và Paris",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v21-54.jpg",
    link: "OB54/v21-54.html",
  },
  {
    title: "Mod Skin FF OB54 V20 Set Đồ Thỏ Thiên Hà Và Thỏ Đen",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v20-54.jpg",
    link: "OB54/v20-54.html",
  },
  {
    title: "Mod Skin FF OB54 V19 Hoạt Ảnh Hồi Máu Thần Ma",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v19-54.jpg",
    link: "OB54/v19-54.html",
  },
  {
    title: "Mod Skin FF OB54 V18 Set Đồ Áo Nagi và isagi",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Nhân Vật: Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v18-54.jpg",
    link: "OB54/v18-54.html",
  },
  {
    title: "Mod Skin FF OB54 V17 Set Đồ Tuyển Thủ Cyrus",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v17-54.jpg",
    link: "OB54/v17-54.html",
  },
  {
    title: "Mod Skin FF OB54 V16 Tung Tung Và Squid Game",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Nhân Vật: Kapella hoặc Ignis ",
    desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v16-54.jpg",
    link: "OB54/v16-54.html",
  },
  {
    title: "Mod Skin FF OB54 V15 Set Đồ Đôi Áo Đá Bóng Bá Sàn",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v15-54.jpg",
    link: "OB54/v15-54.html",
  },
  {
    title: "Mod Skin FF OB54 V14 Set Đồ Đôi Áo Blue Lock Bá Sàn",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    desc: "Nhân Vật: Kapella hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    // desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v14-54.jpg",
    link: "OB54/v14-54.html",
  },
  {
    title: "Mod Skin FF OB54 V13 Hoạt Ảnh Mộng Cảnh",
    // desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    desc: "Bật hoạt ảnh mới FF Max",
    img: "images/v13-54.jpg",
    link: "OB54/v13-54.html",
  },
  {
    title: "Mod Skin FF OB54 V12 Súng M1887 Thánh Phồng Và Vũ Trụ Hủy Diệt",
    desc: "Súng: M1887 Phong Xà hoặc Ánh Sao",
    // desc: "Súng: Lục bảng thẻ boyahh",
    // desc: "Nhân Vật: Alok thức tỉnh hoặc Ignis ",
    // desc: "Hành động: Bắn nè",
    img: "images/v12-54.jpg",
    link: "OB54/v12-54.html",
  },
];
